name: CI

on:
  pull_request:
  push:
    branches:
      - main
      - develop

jobs:
  call-high-workflow:
    uses: devkishore/rn-monorepo/.github/workflows/checks-high.yml@main
    secrets: inherit
